title: Sonora.Chat Blog
description: Automated articles about music, streaming, technology and AI
baseurl: "/sonorachat-blog"
url: "https://atomics13.github.io"
github_username: atomics13

# Theme
theme: minima
layout: home
# SEO Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Posts Configuration
permalink: /blog/:title/
show_excerpts: true
excerpt_separator: "<!--more-->"

# Minima Theme Settings
minima:
  date_format: "%B %d, %Y"
  social_links:
    github: atomics13
